# TODO - change to more user-friendly names

DEPARTMENT_LIST = [
	{"abbreviation":"ACFM", "name":"Accounting & Financial Management"},
	{"abbreviation":"AFST", "name":"Africana Studies"},
	{"abbreviation":"ANBE", "name":"Animal Behavior"},
	{"abbreviation":"ANTH", "name":"Anthropology"},
	{"abbreviation":"ARBC", "name":"Arabic"},
	{"abbreviation":"ARTH", "name":"Art History"},
	{"abbreviation":"ARST", "name":"Art Studio"},
	{"abbreviation":"ASTR", "name":"Astronomy"},
	{"abbreviation":"BIOL", "name":"Biology"},
	{"abbreviation":"BMEG", "name":"Biomedical Engineering"},
	{"abbreviation":"CHEG", "name":"Chemical Engineering"},
	{"abbreviation":"CHEM", "name":"Chemistry"},
	{"abbreviation":"CHIN", "name":"Chinese"},
	{"abbreviation":"CEEG", "name":"Civil & Environmental Engineering"},
	{"abbreviation":"CLAS", "name":"Classics"},
	{"abbreviation":"CSCI", "name":"Computer Science"},
	{"abbreviation":"ENCW", "name":"Creative Writing"},
	{"abbreviation":"DANC", "name":"Dance"},
	{"abbreviation":"EAST", "name":"East Asian Studies"},
	{"abbreviation":"ECON", "name":"Economics"},
	{"abbreviation":"EDUC", "name":"Education"},
	{"abbreviation":"ECEG", "name":"Electrical & Computer Engineering"},
	{"abbreviation":"ENGR", "name":"Engineering"},
	{"abbreviation":"ENGL", "name":"English"},
	{"abbreviation":"ENST", "name":"Environmental Studies"},
	{"abbreviation":"ENFS", "name":"Film/Media Studies"},
	{"abbreviation":"FOUN", "name":"Foundation Seminar"},
	{"abbreviation":"FREN", "name":"French"},
	{"abbreviation":"GEOG", "name":"Geography"},
	{"abbreviation":"GEOL", "name":"Geology"},
	{"abbreviation":"GRMN", "name":"German"},
	{"abbreviation":"GLBM", "name":"Global Management"},
	{"abbreviation":"GREK", "name":"Greek"},
	{"abbreviation":"HEBR", "name":"Hebrew"},
	{"abbreviation":"HIST", "name":"History"},
	{"abbreviation":"HUMN", "name":"Humanities"},
	{"abbreviation":"IREL", "name":"International Relations"},
	{"abbreviation":"ITAL", "name":"Italian"},
	{"abbreviation":"JAPN", "name":"Japanese"},
	{"abbreviation":"LATN", "name":"Latin"},
	{"abbreviation":"LAMS", "name":"Latin American Studies"},
	{"abbreviation":"LING", "name":"Linguistics"},
	{"abbreviation":"ENLS", "name":"Literary Studies"},
	{"abbreviation":"MGMT", "name":"Management"},
	{"abbreviation":"MSUS", "name":"Managing for Sustainability"},
	{"abbreviation":"MIDE", "name":"Markets, Innovation & Design"},
	{"abbreviation":"MATH", "name":"Mathematics"},
	{"abbreviation":"MECH", "name":"Mechanical Engineering"},
	{"abbreviation":"MILS", "name":"Military Science"},
	{"abbreviation":"MUSC", "name":"Music"},
	{"abbreviation":"NEUR", "name":"Neuroscience"},
	{"abbreviation":"PHIL", "name":"Philosophy"},
	{"abbreviation":"PHYS", "name":"Physics"},
	{"abbreviation":"POLS", "name":"Political Science"},
	{"abbreviation":"PSYC", "name":"Psychology"},
	{"abbreviation":"RELI", "name":"Religion"},
	{"abbreviation":"RESC", "name":"Residential Colleges"},
	{"abbreviation":"RUSS", "name":"Russian"},
	{"abbreviation":"SIGN", "name":"Sign Language"},
	{"abbreviation":"SOCI", "name":"Sociology"},
	{"abbreviation":"SPAN", "name":"Spanish"},
	{"abbreviation":"THEA", "name":"Theatre"},
	{"abbreviation":"UNIV", "name":"University Course"},
	{"abbreviation":"WMST", "name":"Women's and Gender Studies"}
]

CCC_LIST = [
	{"abbreviation": "ARHC", "name": "Arts and Humanities"},
	{"abbreviation": "AHLG", "name": "Arts and Humanities Learning Goals"},
	{"abbreviation": "CBL", "name": "Community Based Learning"},
	{"abbreviation": "DUSC", "name": "Diversity in the U.S."},
	{"abbreviation": "GLSP", "name": "Engineering Global and Societal Perspectives"},
	{"abbreviation": "EGHU", "name": "Engineering Humanities"},
	{"abbreviation": "EGSS", "name": "Engineering Social Science"},
	{"abbreviation": "EVCN", "name": "Environmental Connections"},
	{"abbreviation": "FRST", "name": "First year course"},
	{"abbreviation": "CCFL", "name": "Foreign Language"},
	{"abbreviation": "FOUN", "name": "Foundation Seminar"},
	{"abbreviation": "GBCC", "name": "Global Connections"},
	{"abbreviation": "CCIP", "name": "Integrated Perspectives"},
	{"abbreviation": "LBSC", "name": "Lab Science"},
	{"abbreviation": "NSMC", "name": "Natural Science and Mathematics"},
	{"abbreviation": "NMLG", "name": "Natural Science and Mathematics Learning Goals"},
	{"abbreviation": "CCQR", "name": "Quantitative Reasoning"},
	{"abbreviation": "SL", "name": "Service Learning Course"},
	{"abbreviation": "SLSC", "name": "Social Science"},
	{"abbreviation": "SSLG", "name": "Social Science Learning Goals"},
	{"abbreviation": "W1", "name": "Writing Level 1"},
	{"abbreviation": "W2", "name": "Writing Level 2"},
]

CREDIT_LIST = [
	{"abbreviation": ".5", "name": "Half Credit"},
	{"abbreviation": ".25", "name": "Quarter Credit"}
]
