DEPARTMENT_LIST = [
	{"short":"ACFM", "long":"Accounting & Financial Management"},
	{"short":"AFST", "long":"Africana Studies"},
	{"short":"ANBE", "long":"Animal Behavior"},
	{"short":"ANTH", "long":"Anthropology"},
	{"short":"ARBC", "long":"Arabic"},
	{"short":"ARTH", "long":"Art History"},
	{"short":"ARST", "long":"Art Studio"},
	{"short":"ASTR", "long":"Astronomy"},
	{"short":"BIOL", "long":"Biology"},
	{"short":"BMEG", "long":"Biomedical Engineering"},
	{"short":"CHEG", "long":"Chemical Engineering"},
	{"short":"CHEM", "long":"Chemistry"},
	{"short":"CHIN", "long":"Chinese"},
	{"short":"CEEG", "long":"Civil & Environmental Engineering"},
	{"short":"CLAS", "long":"Classics"},
	{"short":"CSCI", "long":"Computer Science"},
	{"short":"ENCW", "long":"Creative Writing"},
	{"short":"DANC", "long":"Dance"},
	{"short":"EAST", "long":"East Asian Studies"},
	{"short":"ECON", "long":"Economics"},
	{"short":"EDUC", "long":"Education"},
	{"short":"ECEG", "long":"Electrical & Computer Engineering"},
	{"short":"ENGR", "long":"Engineering"},
	{"short":"ENGL", "long":"English"},
	{"short":"ENST", "long":"Environmental Studies"},
	{"short":"ENFS", "long":"Film/Media Studies"},
	{"short":"FOUN", "long":"Foundation Seminar"},
	{"short":"FREN", "long":"French"},
	{"short":"GEOG", "long":"Geography"},
	{"short":"GEOL", "long":"Geology"},
	{"short":"GRMN", "long":"German"},
	{"short":"GLBM", "long":"Global Management"},
	{"short":"GREK", "long":"Greek"},
	{"short":"HEBR", "long":"Hebrew"},
	{"short":"HIST", "long":"History"},
	{"short":"HUMN", "long":"Humanities"},
	{"short":"IREL", "long":"International Relations"},
	{"short":"ITAL", "long":"Italian"},
	{"short":"JAPN", "long":"Japanese"},
	{"short":"LATN", "long":"Latin"},
	{"short":"LAMS", "long":"Latin American Studies"},
	{"short":"LING", "long":"Linguistics"},
	{"short":"ENLS", "long":"Literary Studies"},
	{"short":"MGMT", "long":"Management"},
	{"short":"MSUS", "long":"Managing for Sustainability"},
	{"short":"MIDE", "long":"Markets, Innovation & Design"},
	{"short":"MATH", "long":"Mathematics"},
	{"short":"MECH", "long":"Mechanical Engineering"},
	{"short":"MILS", "long":"Military Science"},
	{"short":"MUSC", "long":"Music"},
	{"short":"NEUR", "long":"Neuroscience"},
	{"short":"PHIL", "long":"Philosophy"},
	{"short":"PHYS", "long":"Physics"},
	{"short":"POLS", "long":"Political Science"},
	{"short":"PSYC", "long":"Psychology"},
	{"short":"RELI", "long":"Religion"},
	{"short":"RESC", "long":"Residential Colleges"},
	{"short":"RUSS", "long":"Russian"},
	{"short":"SIGN", "long":"Sign Language"},
	{"short":"SOCI", "long":"Sociology"},
	{"short":"SPAN", "long":"Spanish"},
	{"short":"THEA", "long":"Theatre"},
	{"short":"UNIV", "long":"University Course"},
	{"short":"WMST", "long":"Women's and Gender Studies"}
]

CCC_LIST = [
	{"shortCCC": "ARHC", "long": "Arts and Humanities"},
	{"shortCCC": "AHLG", "long": "Arts and Humanities Learning Goals"},
	{"shortCCC": "CBL", "long": "Community Based Learning"},
	{"shortCCC": "DUSC", "long": "Diversity in the U.S."},
	{"shortCCC": "GLSP", "long": "Engineering Global and Societal Perspectives"},
	{"shortCCC": "EGHU", "long": "Engineering Humanities"},
	{"shortCCC": "EGSS", "long": "Engineering Social Science"},
	{"shortCCC": "EVCN", "long": "Environmental Connections"},
	{"shortCCC": "FRST", "long": "First year course"},
	{"shortCCC": "CCFL", "long": "Foreign Language"},
	{"shortCCC": "FOUN", "long": "Foundation Seminar"},
	{"shortCCC": "GBCC", "long": "Global Connections"},
	{"shortCCC": "CCIP", "long": "Integrated Perspectives"},
	{"shortCCC": "LBSC", "long": "Lab Science"},
	{"shortCCC": "NSMC", "long": "Natural Science and Mathematics"},
	{"shortCCC": "NMLG", "long": "Natural Science and Mathematics Learning Goals"},
	{"shortCCC": "CCQR", "long": "Quantitative Reasoning"},
	{"shortCCC": "SL", "long": "Service Learning Course"},
	{"shortCCC": "SLSC", "long": "Social Science"},
	{"shortCCC": "SSLG", "long": "Social Science Learning Goals"},
	{"shortCCC": "W1", "long": "Writing Level 1"},
	{"shortCCC": "W2", "long": "Writing Level 2"},
]

CREDIT_LIST = [
	{"shortCred": ".5", "long": "Half Credit"},
	{"shortCred": ".25", "long": "Quarter Credit"}
]
